// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogCategories
    {
        public BlogCategories()
        {
            BlogEntryCategories = new HashSet<BlogEntryCategories>();
        }

        public int CatId { get; set; }
        public string Category { get; set; }
        public string Slug { get; set; }
        public int? ParentId { get; set; }
        public int PortalId { get; set; }

        public virtual ICollection<BlogEntryCategories> BlogEntryCategories { get; set; }
    }
}