// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogEntryCategories
    {
        public int EntryCatId { get; set; }
        public int? EntryId { get; set; }
        public int? CatId { get; set; }

        public virtual BlogCategories Cat { get; set; }
        public virtual BlogEntries Entry { get; set; }
    }
}