// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogBlogs
    {
        public int PortalId { get; set; }
        public int BlogId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Public { get; set; }
        public bool AllowComments { get; set; }
        public bool AllowAnonymous { get; set; }
        public DateTime? LastEntry { get; set; }
        public DateTime Created { get; set; }
        public bool ShowFullName { get; set; }
        public string DateFormat { get; set; }
        public string Culture { get; set; }
        public int TimeZone { get; set; }
        public int? ParentBlogId { get; set; }
        public bool Syndicated { get; set; }
        public bool SyndicateIndependant { get; set; }
        public string SyndicationUrl { get; set; }
        public string SyndicationEmail { get; set; }
        public bool? EmailNotification { get; set; }
        public bool? AllowTrackbacks { get; set; }
        public bool? AutoTrackback { get; set; }
        public bool? MustApproveComments { get; set; }
        public bool? MustApproveAnonymous { get; set; }
        public bool? MustApproveTrackbacks { get; set; }
        public bool? UseCaptcha { get; set; }
    }
}