// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogEntryTags
    {
        public int EntryTagId { get; set; }
        public int EntryId { get; set; }
        public int TagId { get; set; }

        public virtual BlogEntries Entry { get; set; }
        public virtual BlogTags Tag { get; set; }
    }
}