// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogSettings
    {
        public int PortalId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int TabId { get; set; }
    }
}