// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorBlogs.Data.Models
{
    public partial class Logs
    {
        public int LogId { get; set; }
        public DateTime LogDate { get; set; }
        public string LogAction { get; set; }
        public string LogUserName { get; set; }
        public string LogIpaddress { get; set; }
    }
}