// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotNetNukeBlogs.Data.Models
{
    public partial class BlogComments
    {
        public int CommentId { get; set; }
        public int EntryId { get; set; }
        public int? UserId { get; set; }
        public string Comment { get; set; }
        public DateTime AddedDate { get; set; }
        public string Title { get; set; }
        public bool? Approved { get; set; }
        public string Author { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }

        public virtual BlogEntries Entry { get; set; }
    }
}