// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorBlogs.Data.Models
{
    public partial class BlogCategory
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public int CategoryId { get; set; }

        public virtual Blogs Blog { get; set; }
        public virtual Categorys Category { get; set; }
    }
}