// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorBlogs.Data.Models;

public partial class Newsletters
{
    public int Id { get; set; }

    public DateTime NewsletterDate { get; set; }

    public string NewsletterTitle { get; set; }

    public string NewsletterContent { get; set; }

    public DateTime Created { get; set; }

    public DateTime? Updated { get; set; }

    public virtual ICollection<NewslettersCampain> NewslettersCampain { get; set; } = new List<NewslettersCampain>();
}