// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorBlogs.Data.Models;

public partial class NewslettersLogs
{
    public int Id { get; set; }

    public int NewsletterCampainId { get; set; }

    public string LogType { get; set; }

    public string UserName { get; set; }

    public string LogDetails { get; set; }

    public virtual NewslettersCampain NewsletterCampain { get; set; }
}